dingbot:
  prefix: https://oapi.dingtalk.com/robot/send
  access-token: change-to-your-access-token
  secret:
    secret-enabled: false
    secret-token: change-to-your-secret-token

monitor:
  flow-usage:
    daily-threshold: 1048576
    monthly-threshold: 31457280


logging:
  level:
    com.xyzla: debug
    org.apache: warn
    org.springframework: warn
    com.netflix: warn
    com.amazon.sqs: error