spring:
  redis:
    pool:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: 5000
    host: 192.168.31.51
    port: 30020
    timeout: 5000
    database: 1

logging:
  level:
    com.xyzla: debug
    org.apache: warn
    org.springframework: warn
    com.netflix: warn
    com.amazon.sqs: error